version: '3.8'

services:
  # Authentication Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"  # Exposes auth-service on port 8000
    environment:
      DATABASE_NAME: auth_service_db
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
    depends_on:
      - mongodb
      - rabbitmq

  # Job Posting Service
  job-post-service:
    build: ./job-post-service
    container_name: job-post-service
    ports:
      - "8001:8001"  # Exposes job-post-service on port 8001
    environment:
      DATABASE_NAME: job_post_service_db
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
    depends_on:
      - mongodb
      - rabbitmq

  # Job Search Service
  job-search-service:
    build: ./job-search-service
    container_name: job-search-service
    ports:
      - "8002:8002"  # Exposes job-search-service on port 8002
    environment:
      DATABASE_NAME: job_search_service_db
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
    depends_on:
      - mongodb
      - rabbitmq

  # MongoDB Service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposes MongoDB on port 27017
    volumes:
      - mongodb_data:/data/db

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # RabbitMQ messaging port
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongodb_data:
